name: Run Flake8 Against Repository

on:
  push:

jobs:
  flake8-lint:
    runs-on: macos-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "E501,E302,W293,W291,E303"  