name: Run Flake8 Against Repository

on:
  push:
    paths:
      - './*.py'
      - './*/*.py'
  pull_request:
    paths:
      - './*.py'
      - './*/*.py'
#  schedule:
#    - cron: "0 12 * * *" # Runs at 12 UTC (i.e. 2 p.m. CET/CEST - 5 a.m. PST) every day
#    paths:
#      - './*.py'
#      - './GoogleSheetsAndForms/*.py'
  workflow_dispatch:
    paths:
      - './*.py'
      - './*/*.py'
      
jobs:
  flake8-lint:
    runs-on: macos-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          ignore: "E501,E302,W293"        
  
