# This is a basic workflow to help you get started with Actions

name: Projects for Ugrad Students

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 0,12 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  projects-ugrad:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: install required packages
        run: |
          pip install gspread oauth2client
          pip install --upgrade google-api-python-client

      - name: set-environment-vars
        uses: microsoft/variable-substitution@v1 
        id: create-env
        with:
          files: './data/riscattoPuntiCanale.json'
        env:
          private_key_id: ${{ secrets.PRIVATE_KEY_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          client_id: ${{ secrets.CLIENT_ID }}
          client_email: ${{ secrets.CLIENT_EMAIL }}
          client_x509_cert_url: ${{ secrets.CLIENT_CERT_URI }}
          
      - name: execute py script
        run: |
          export workingDir=(`pwd`)
          export PYTHONPATH="${PYTHONPATH}:${workingDir}"
          python3 ./macros/progettiUgrads.py --json ./data/riscattoPuntiCanale.json --ref ./data/projectsUgrad.json

