# This is a basic workflow to help you get started with Actions

name: Sync Google Sheet and compile Forms

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 12 * * *" # Runs at 12 UTC (i.e. 2 p.m. CET/CEST - 5 a.m. PST) every day
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-code:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: install required packages
        run: |
          pip install gspread oauth2client
          pip install --upgrade google-api-python-client

      - name: execute py script
        run: |
            python3 RiscattoPuntiCanaleGravier.py
        
